name: Fortnite Updates to Discord

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch: {}

permissions:
  contents: write   # allow committing the updated state file

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4

      - name: Run notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          STATE_PATH: state/fortnite_state.json
          ENABLE_CROWDSIZE: "false"   # set to "true" if you want Reddit size range
        run: |
          python scripts/fortnite_update_notifier.py

      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state/fortnite_state.json
            git commit -m "chore: update fortnite_state.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
