# .github/workflows/fortnite_updates.yml
name: Fortnite Updates to Discord

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Repo root:" && pwd
          ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4
      - env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          STATE_PATH: state/fortnite_state.json
        run: python fortnite_update_notifier.py --force
      - run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state/fortnite_state.json
            git commit -m "chore: update fortnite_state.json [skip ci]"
            git push
          else
            echo "No state changes."
          fi

